inherit_from: .rubocop_todo.yml

require:
  - rubocop-rails

AllCops:
  NewCops: enable
  Exclude:
    - 'db/**/*'
    - 'bin/**/*'
    - 'Gemfile'
    - 'Rakefile'
    - 'node_modules/**/*'

Layout/LineLength:
  Max: 120
  Exclude:
    - 'spec/models/html_sanitizer_spec.rb'
    - 'config/initializers/devise.rb'
    - 'app/models/importers/submission_response_importer.rb'

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Exclude:
    - spec/**/*

Style/TrailingCommaInArguments:
  Enabled: false

Style/TrailingCommaInHashLiteral:
  Enabled: false

Style/TrailingCommaInArrayLiteral:
  Enabled: false
