version: 2.1

commands:
  bundle_install_cmd:
    description: 'Perform bundler installation, relying on CircleCI cache for performance'
    steps:
      - restore_cache:
          keys:
            - bundler-cache-{{ checksum ".ruby-version" }}-{{ checksum "Gemfile.lock" }}
      - run:
          name: 'Bundle install'
          command: |
            bundle config set frozen 'true'
            bundle install --path=.bundle
      - save_cache:
          key: bundler-cache-{{ checksum ".ruby-version" }}-{{ checksum "Gemfile.lock" }}
          paths:
            - .bundle
  yarn_install_cmd:
    description: 'Perform node module installation, relying on CircleCI cache for performance'
    steps:
      - restore_cache:
          keys:
            - node-cache-{{ checksum "package.json" }}-{{ checksum "yarn.lock" }}
      - run:
          name: 'Yarn install'
          command: bin/yarn install
      - save_cache:
          key: node-cache-{{ checksum "package.json" }}-{{ checksum "yarn.lock" }}
          paths:
            - node_modules
  webpacker_compile_cmd:
    steps:
      - run:
          name: 'Generate file containing checksums of all our javascript source'
          command: |
            find app/javascript -type f -exec md5sum {} + | LC_ALL=C sort > tmp/app_javascript_checksums.txt
      - restore_cache:
          keys:
            - webpacker-cache-{{ checksum "Gemfile.lock" }}-{{ checksum "yarn.lock" }}-{{ checksum "tmp/app_javascript_checksums.txt" }}
      - run:
          name: 'Compile webpacker assets'
          command: |
            bundle config path .bundle
            bundle exec rails webpacker:compile
      - save_cache:
          key: webpacker-cache-{{ checksum "Gemfile.lock" }}-{{ checksum "yarn.lock" }}-{{ checksum "tmp/app_javascript_checksums.txt" }}
          paths:
            - public/packs-test
            - tmp/cache/webpacker # should match the cache_path entry in config/webpacker.yml
  rubocop_cmd:
    description: 'Run rubocop'
    steps:
      - run:
          name: 'Run rubocop'
          command: |
            bundle config path .bundle
            bundle exec rubocop
  rspec_cmd:
    parameters:
      specs:
        type: string
        default: spec
      output:
        type: string
        default: /tmp/rspec/rspec.xml
    steps:
      - run:
          name: 'Run rspec'
          command: |
            bundle config path .bundle
            bundle exec rails db:create
            bundle exec rspec --format progress --format RspecJunitFormatter -o << parameters.output >> << parameters.specs >>
  mocha_cmd:
    description: 'Run mocha specs'
    parameters:
      output:
        type: string
        default: /tmp/mocha/mocha.xml
    steps:
      - run:
          name: 'Run mocha specs'
          command: yarn test --reporter mocha-junit-reporter
          environment:
            MOCHA_FILE: << parameters.output >>

executors:
  app_only:
    shell: /bin/bash -euxo pipefail
    docker:
      - image: circleci/ruby:2.7.2-node
  app_and_db:
    shell: /bin/bash -euxo pipefail
    docker:
      - image: circleci/ruby:2.7.2-node-browsers
        environment:
          POSTGRES_HOST: 127.0.0.1
          RAILS_ENV: test
      - image: circleci/postgres:latest
        environment:
          POSTGRES_DB: mutualaid_test
          POSTGRES_HOST_AUTH_METHOD: trust
          POSTGRES_USER: circleci

jobs:
  bundle:
    executor: app_only
    steps:
      - checkout
      - bundle_install_cmd
      - persist_to_workspace:
          root: .
          paths: [.bundle]
  yarn:
    executor: app_only
    steps:
      - checkout
      - yarn_install_cmd
      - persist_to_workspace:
          root: .
          paths: [node_modules]
  webpacker:
    executor: app_only
    environment:
      RAILS_ENV: test
    steps:
      - checkout
      - attach_workspace: {at: .}
      - webpacker_compile_cmd
      - persist_to_workspace:
          root: .
          paths: [public/packs-test]
  rubocop:
    executor: app_only
    steps:
      - checkout
      - attach_workspace: {at: .}
      - rubocop_cmd
  backend_specs:
    executor: app_and_db
    steps:
      - checkout
      - attach_workspace: {at: .}
      - rspec_cmd: {output: /tmp/rspec_backend/rspec.xml}
      - store_test_results: {path: /tmp/rspec_backend}
  frontend_specs:
    executor: app_only
    steps:
      - checkout
      - attach_workspace: {at: .}
      - mocha_cmd: {output: /tmp/mocha/mocha.xml}
      - store_test_results: {path: /tmp/mocha}
      - store_artifacts: {path: /tmp/mocha}
  system_specs:
    executor: app_and_db
    environment:
      HEADLESS_CHROME: true
    steps:
      - checkout
      - attach_workspace: {at: .}
      - rspec_cmd:
          specs: spec/system
          output: /tmp/rspec_system/rspec.xml
      - store_test_results: {path: /tmp/rspec_system}

workflows:
  version: 2.1
  mutual_aid:
    jobs:
      - bundle
      - yarn
      - rubocop:
          requires:
            - bundle
      - backend_specs:
          requires:
            - bundle
            - yarn
      - frontend_specs:
          requires:
            - yarn
      - webpacker:
          requires:
            - bundle
            - yarn
      - system_specs:
          requires:
            - bundle
            - yarn
            - webpacker
